// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="equalizer_equalizer,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020i-clg484-1L,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.186000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=0,HLS_SYN_FF=10662,HLS_SYN_LUT=9965,HLS_VERSION=2021_1}" *)

module equalizer (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sample_in_V_dout,
        sample_in_V_empty_n,
        sample_in_V_read,
        sample_out_V_din,
        sample_out_V_full_n,
        sample_out_V_write,
        new_lts_Addr_A,
        new_lts_EN_A,
        new_lts_WEN_A,
        new_lts_Din_A,
        new_lts_Dout_A,
        new_lts_Clk_A,
        new_lts_Rst_A,
        nof_ofdm_sym,
        ht,
        prev_PEG,
        ap_return
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] sample_in_V_dout;
input   sample_in_V_empty_n;
output   sample_in_V_read;
output  [31:0] sample_out_V_din;
input   sample_out_V_full_n;
output   sample_out_V_write;
output  [31:0] new_lts_Addr_A;
output   new_lts_EN_A;
output  [3:0] new_lts_WEN_A;
output  [31:0] new_lts_Din_A;
input  [31:0] new_lts_Dout_A;
output   new_lts_Clk_A;
output   new_lts_Rst_A;
input  [11:0] nof_ofdm_sym;
input  [0:0] ht;
input  [31:0] prev_PEG;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg sample_in_V_read;
reg sample_out_V_write;
reg[31:0] new_lts_Addr_A;
reg new_lts_EN_A;

(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [6:0] POLARITY_V_address0;
reg    POLARITY_V_ce0;
wire   [0:0] POLARITY_V_q0;
reg   [1:0] ht_pol_nr_V;
reg   [8:0] atan_lut_V_address0;
reg    atan_lut_V_ce0;
wire   [8:0] atan_lut_V_q0;
reg   [5:0] DATA_SC_IDX_52_V_address0;
reg    DATA_SC_IDX_52_V_ce0;
wire   [5:0] DATA_SC_IDX_52_V_q0;
reg   [5:0] DATA_SC_IDX_48_V_address0;
reg    DATA_SC_IDX_48_V_ce0;
wire   [5:0] DATA_SC_IDX_48_V_q0;
wire   [0:0] ht_read_read_fu_222_p2;
wire    ap_CS_fsm_state3;
wire   [4:0] select_ln3_fu_465_p3;
reg   [4:0] select_ln3_reg_877;
wire   [11:0] i_V_6_fu_486_p2;
reg   [11:0] i_V_6_reg_886;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state6;
wire   [0:0] current_polarity_V_1_fu_603_p2;
reg   [0:0] current_polarity_V_1_reg_896;
wire    ap_CS_fsm_state7;
reg   [31:0] prev_PEG_V_load_reg_902;
wire    ap_CS_fsm_state8;
wire   [11:0] grp_cpe_estimate_fu_329_ap_return;
reg   [11:0] cpe_V_reg_908;
wire  signed [15:0] sext_ln41_fu_639_p1;
reg   [15:0] sext_ln41_reg_913;
wire   [17:0] trunc_ln70_fu_644_p1;
reg   [17:0] trunc_ln70_reg_918;
wire   [48:0] trunc_ln1543_fu_670_p1;
reg   [48:0] trunc_ln1543_reg_926;
wire    ap_CS_fsm_state12;
reg   [0:0] tmp_reg_931;
reg   [15:0] tmp_16_reg_937;
reg   [14:0] tmp_15_reg_942;
wire    ap_CS_fsm_state13;
reg   [5:0] symbol_iq_M_real_V_address0;
reg    symbol_iq_M_real_V_ce0;
reg    symbol_iq_M_real_V_we0;
wire   [15:0] symbol_iq_M_real_V_q0;
reg   [5:0] symbol_iq_M_imag_V_address0;
reg    symbol_iq_M_imag_V_ce0;
reg    symbol_iq_M_imag_V_we0;
wire   [15:0] symbol_iq_M_imag_V_q0;
reg   [5:0] sym_phase_V_address0;
reg    sym_phase_V_ce0;
reg    sym_phase_V_we0;
reg   [17:0] sym_phase_V_d0;
wire   [17:0] sym_phase_V_q0;
wire    grp_lvpe_correction_fu_290_ap_start;
wire    grp_lvpe_correction_fu_290_ap_done;
wire    grp_lvpe_correction_fu_290_ap_idle;
wire    grp_lvpe_correction_fu_290_ap_ready;
wire   [5:0] grp_lvpe_correction_fu_290_sym_phase_address0;
wire    grp_lvpe_correction_fu_290_sym_phase_ce0;
wire    grp_lvpe_correction_fu_290_sym_phase_we0;
wire   [17:0] grp_lvpe_correction_fu_290_sym_phase_d0;
wire    grp_equalizer_Pipeline_lts_pilot_fu_307_ap_start;
wire    grp_equalizer_Pipeline_lts_pilot_fu_307_ap_done;
wire    grp_equalizer_Pipeline_lts_pilot_fu_307_ap_idle;
wire    grp_equalizer_Pipeline_lts_pilot_fu_307_ap_ready;
wire   [31:0] grp_equalizer_Pipeline_lts_pilot_fu_307_new_lts_Addr_A;
wire    grp_equalizer_Pipeline_lts_pilot_fu_307_new_lts_EN_A;
wire   [3:0] grp_equalizer_Pipeline_lts_pilot_fu_307_new_lts_WEN_A;
wire   [31:0] grp_equalizer_Pipeline_lts_pilot_fu_307_new_lts_Din_A;
wire   [15:0] grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_3_024_out;
wire    grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_3_024_out_ap_vld;
wire   [15:0] grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_2_023_out;
wire    grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_2_023_out_ap_vld;
wire   [15:0] grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_1_022_out;
wire    grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_1_022_out_ap_vld;
wire   [15:0] grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_0_021_out;
wire    grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_0_021_out_ap_vld;
wire   [15:0] grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_3_020_out;
wire    grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_3_020_out_ap_vld;
wire   [15:0] grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_2_019_out;
wire    grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_2_019_out_ap_vld;
wire   [15:0] grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_1_018_out;
wire    grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_1_018_out_ap_vld;
wire   [15:0] grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_0_017_out;
wire    grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_0_017_out_ap_vld;
wire    grp_equalizer_Pipeline_symbol_iq_fu_321_ap_start;
wire    grp_equalizer_Pipeline_symbol_iq_fu_321_ap_done;
wire    grp_equalizer_Pipeline_symbol_iq_fu_321_ap_idle;
wire    grp_equalizer_Pipeline_symbol_iq_fu_321_ap_ready;
wire    grp_equalizer_Pipeline_symbol_iq_fu_321_sample_in_V_read;
wire   [5:0] grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_real_V_address0;
wire    grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_real_V_ce0;
wire    grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_real_V_we0;
wire   [15:0] grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_real_V_d0;
wire   [5:0] grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_imag_V_address0;
wire    grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_imag_V_ce0;
wire    grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_imag_V_we0;
wire   [15:0] grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_imag_V_d0;
wire    grp_cpe_estimate_fu_329_ap_start;
wire    grp_cpe_estimate_fu_329_ap_done;
wire    grp_cpe_estimate_fu_329_ap_idle;
wire    grp_cpe_estimate_fu_329_ap_ready;
wire   [5:0] grp_cpe_estimate_fu_329_sample_in_M_real_0_0_0_address0;
wire    grp_cpe_estimate_fu_329_sample_in_M_real_0_0_0_ce0;
wire   [5:0] grp_cpe_estimate_fu_329_sample_in_M_imag_0_0_0_address0;
wire    grp_cpe_estimate_fu_329_sample_in_M_imag_0_0_0_ce0;
wire   [8:0] grp_cpe_estimate_fu_329_atan_lut_V_address0;
wire    grp_cpe_estimate_fu_329_atan_lut_V_ce0;
wire    grp_equalizer_Pipeline_lvpe_est_fu_352_ap_start;
wire    grp_equalizer_Pipeline_lvpe_est_fu_352_ap_done;
wire    grp_equalizer_Pipeline_lvpe_est_fu_352_ap_idle;
wire    grp_equalizer_Pipeline_lvpe_est_fu_352_ap_ready;
wire   [5:0] grp_equalizer_Pipeline_lvpe_est_fu_352_sym_phase_V_address0;
wire    grp_equalizer_Pipeline_lvpe_est_fu_352_sym_phase_V_ce0;
wire   [5:0] grp_equalizer_Pipeline_lvpe_est_fu_352_symbol_iq_M_real_V_address0;
wire    grp_equalizer_Pipeline_lvpe_est_fu_352_symbol_iq_M_real_V_ce0;
wire   [5:0] grp_equalizer_Pipeline_lvpe_est_fu_352_symbol_iq_M_imag_V_address0;
wire    grp_equalizer_Pipeline_lvpe_est_fu_352_symbol_iq_M_imag_V_ce0;
wire   [18:0] grp_equalizer_Pipeline_lvpe_est_fu_352_Sxy_V_1_out;
wire    grp_equalizer_Pipeline_lvpe_est_fu_352_Sxy_V_1_out_ap_vld;
wire   [8:0] grp_equalizer_Pipeline_lvpe_est_fu_352_atan_lut_V_address0;
wire    grp_equalizer_Pipeline_lvpe_est_fu_352_atan_lut_V_ce0;
wire   [15:0] grp_equalizer_Pipeline_lvpe_est_fu_352_grp_rotate_fu_947_p_din1;
wire   [15:0] grp_equalizer_Pipeline_lvpe_est_fu_352_grp_rotate_fu_947_p_din2;
wire   [15:0] grp_equalizer_Pipeline_lvpe_est_fu_352_grp_rotate_fu_947_p_din3;
wire    grp_equalizer_Pipeline_lvpe_est_fu_352_grp_rotate_fu_947_p_ce;
wire    grp_equalizer_Pipeline_lvpe_est_fu_352_grp_rotate_fu_947_p_start;
wire    grp_equalizer_Pipeline_lvpe_corr_fu_381_ap_start;
wire    grp_equalizer_Pipeline_lvpe_corr_fu_381_ap_done;
wire    grp_equalizer_Pipeline_lvpe_corr_fu_381_ap_idle;
wire    grp_equalizer_Pipeline_lvpe_corr_fu_381_ap_ready;
wire   [5:0] grp_equalizer_Pipeline_lvpe_corr_fu_381_sym_phase_V_address0;
wire    grp_equalizer_Pipeline_lvpe_corr_fu_381_sym_phase_V_ce0;
wire    grp_equalizer_Pipeline_lvpe_corr_fu_381_sym_phase_V_we0;
wire   [17:0] grp_equalizer_Pipeline_lvpe_corr_fu_381_sym_phase_V_d0;
wire   [5:0] grp_equalizer_Pipeline_lvpe_corr_fu_381_DATA_SC_IDX_52_V_address0;
wire    grp_equalizer_Pipeline_lvpe_corr_fu_381_DATA_SC_IDX_52_V_ce0;
wire   [5:0] grp_equalizer_Pipeline_lvpe_corr_fu_381_DATA_SC_IDX_48_V_address0;
wire    grp_equalizer_Pipeline_lvpe_corr_fu_381_DATA_SC_IDX_48_V_ce0;
wire  signed [25:0] grp_equalizer_Pipeline_lvpe_corr_fu_381_grp_fu_955_p_din0;
wire   [27:0] grp_equalizer_Pipeline_lvpe_corr_fu_381_grp_fu_955_p_din1;
wire    grp_equalizer_Pipeline_lvpe_corr_fu_381_grp_fu_955_p_ce;
wire    grp_equalizer_Pipeline_eq_per_sym_fu_395_ap_start;
wire    grp_equalizer_Pipeline_eq_per_sym_fu_395_ap_done;
wire    grp_equalizer_Pipeline_eq_per_sym_fu_395_ap_idle;
wire    grp_equalizer_Pipeline_eq_per_sym_fu_395_ap_ready;
wire   [31:0] grp_equalizer_Pipeline_eq_per_sym_fu_395_sample_out_V_din;
wire    grp_equalizer_Pipeline_eq_per_sym_fu_395_sample_out_V_write;
wire   [5:0] grp_equalizer_Pipeline_eq_per_sym_fu_395_sym_phase_V_address0;
wire    grp_equalizer_Pipeline_eq_per_sym_fu_395_sym_phase_V_ce0;
wire   [5:0] grp_equalizer_Pipeline_eq_per_sym_fu_395_symbol_iq_M_real_V_address0;
wire    grp_equalizer_Pipeline_eq_per_sym_fu_395_symbol_iq_M_real_V_ce0;
wire   [5:0] grp_equalizer_Pipeline_eq_per_sym_fu_395_symbol_iq_M_imag_V_address0;
wire    grp_equalizer_Pipeline_eq_per_sym_fu_395_symbol_iq_M_imag_V_ce0;
wire   [31:0] grp_equalizer_Pipeline_eq_per_sym_fu_395_new_lts_Addr_A;
wire    grp_equalizer_Pipeline_eq_per_sym_fu_395_new_lts_EN_A;
wire   [3:0] grp_equalizer_Pipeline_eq_per_sym_fu_395_new_lts_WEN_A;
wire   [31:0] grp_equalizer_Pipeline_eq_per_sym_fu_395_new_lts_Din_A;
wire   [5:0] grp_equalizer_Pipeline_eq_per_sym_fu_395_DATA_SC_IDX_52_V_address0;
wire    grp_equalizer_Pipeline_eq_per_sym_fu_395_DATA_SC_IDX_52_V_ce0;
wire   [5:0] grp_equalizer_Pipeline_eq_per_sym_fu_395_DATA_SC_IDX_48_V_address0;
wire    grp_equalizer_Pipeline_eq_per_sym_fu_395_DATA_SC_IDX_48_V_ce0;
wire   [15:0] grp_equalizer_Pipeline_eq_per_sym_fu_395_grp_rotate_fu_947_p_din1;
wire   [15:0] grp_equalizer_Pipeline_eq_per_sym_fu_395_grp_rotate_fu_947_p_din2;
wire   [15:0] grp_equalizer_Pipeline_eq_per_sym_fu_395_grp_rotate_fu_947_p_din3;
wire    grp_equalizer_Pipeline_eq_per_sym_fu_395_grp_rotate_fu_947_p_ce;
wire    grp_equalizer_Pipeline_eq_per_sym_fu_395_grp_rotate_fu_947_p_start;
reg    grp_rotate_fu_947_ap_start;
wire    grp_rotate_fu_947_ap_done;
wire    grp_rotate_fu_947_ap_idle;
wire    grp_rotate_fu_947_ap_ready;
reg    grp_rotate_fu_947_ap_ce;
reg   [15:0] grp_rotate_fu_947_phase;
reg   [15:0] grp_rotate_fu_947_in_iq_M_real;
reg   [15:0] grp_rotate_fu_947_in_iq_M_imag;
wire   [15:0] grp_rotate_fu_947_ap_return_0;
wire   [15:0] grp_rotate_fu_947_ap_return_1;
wire   [0:0] ret_18_fu_590_p2;
reg   [0:0] current_polarity_V_3_0_reg_247;
wire   [0:0] ret_17_fu_569_p2;
reg   [0:0] current_polarity_V_2_0_reg_258;
wire   [0:0] lhs_V_1_fu_540_p6;
reg   [0:0] ap_phi_mux_p_pn_phi_fu_272_p4;
wire   [0:0] ret_fu_533_p2;
reg   [0:0] current_polarity_V_0_0_reg_279;
reg    grp_lvpe_correction_fu_290_ap_start_reg;
wire    ap_CS_fsm_state9;
reg    grp_equalizer_Pipeline_lts_pilot_fu_307_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_equalizer_Pipeline_symbol_iq_fu_321_ap_start_reg;
wire   [0:0] icmp_ln31_fu_481_p2;
wire    ap_CS_fsm_state5;
reg    grp_cpe_estimate_fu_329_ap_start_reg;
reg    grp_equalizer_Pipeline_lvpe_est_fu_352_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg    grp_equalizer_Pipeline_lvpe_corr_fu_381_ap_start_reg;
reg    grp_equalizer_Pipeline_eq_per_sym_fu_395_ap_start_reg;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire   [63:0] zext_ln573_1_fu_492_p1;
wire   [1:0] fourth_fu_513_p2;
reg   [31:0] prev_PEG_V_fu_156;
wire   [31:0] prev_PEG_V_1_fu_757_p2;
reg   [11:0] i_V_fu_160;
reg   [6:0] pol_nr_V_fu_164;
wire   [6:0] select_ln23_fu_622_p3;
wire   [6:0] select_ln3_1_fu_457_p3;
wire   [1:0] lhs_V_fu_519_p5;
wire   [0:0] lhs_V_fu_519_p6;
wire   [1:0] lhs_V_1_fu_540_p5;
wire   [0:0] lhs_V_2_fu_555_p6;
wire   [1:0] lhs_V_3_fu_576_p5;
wire   [0:0] lhs_V_3_fu_576_p6;
wire   [0:0] icmp_ln1049_fu_610_p2;
wire   [6:0] pol_nr_V_1_fu_616_p2;
wire  signed [11:0] sext_ln41_fu_639_p0;
wire  signed [23:0] r_fu_652_p3;
wire   [25:0] mul_ln1543_1_fu_664_p1;
wire   [49:0] mul_ln1543_1_fu_664_p2;
wire   [48:0] sub_ln1543_fu_692_p2;
wire  signed [23:0] sext_ln1543_4_fu_707_p1;
wire  signed [23:0] sext_ln1543_5_fu_710_p1;
wire   [23:0] select_ln1543_fu_713_p3;
wire   [23:0] sub_ln1543_1_fu_720_p2;
wire   [18:0] tmp_s_fu_726_p4;
wire   [18:0] tmp_2_fu_736_p4;
wire   [18:0] r_2_fu_746_p3;
wire  signed [31:0] sext_ln1676_fu_753_p1;
wire   [51:0] grp_fu_955_p2;
reg    grp_fu_955_ce;
reg   [14:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
#0 ht_pol_nr_V = 2'd0;
#0 grp_lvpe_correction_fu_290_ap_start_reg = 1'b0;
#0 grp_equalizer_Pipeline_lts_pilot_fu_307_ap_start_reg = 1'b0;
#0 grp_equalizer_Pipeline_symbol_iq_fu_321_ap_start_reg = 1'b0;
#0 grp_cpe_estimate_fu_329_ap_start_reg = 1'b0;
#0 grp_equalizer_Pipeline_lvpe_est_fu_352_ap_start_reg = 1'b0;
#0 grp_equalizer_Pipeline_lvpe_corr_fu_381_ap_start_reg = 1'b0;
#0 grp_equalizer_Pipeline_eq_per_sym_fu_395_ap_start_reg = 1'b0;
end

equalizer_POLARITY_V #(
    .DataWidth( 1 ),
    .AddressRange( 127 ),
    .AddressWidth( 7 ))
POLARITY_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(POLARITY_V_address0),
    .ce0(POLARITY_V_ce0),
    .q0(POLARITY_V_q0)
);

equalizer_atan_lut_V #(
    .DataWidth( 9 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
atan_lut_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(atan_lut_V_address0),
    .ce0(atan_lut_V_ce0),
    .q0(atan_lut_V_q0)
);

equalizer_DATA_SC_IDX_52_V #(
    .DataWidth( 6 ),
    .AddressRange( 52 ),
    .AddressWidth( 6 ))
DATA_SC_IDX_52_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DATA_SC_IDX_52_V_address0),
    .ce0(DATA_SC_IDX_52_V_ce0),
    .q0(DATA_SC_IDX_52_V_q0)
);

equalizer_DATA_SC_IDX_48_V #(
    .DataWidth( 6 ),
    .AddressRange( 48 ),
    .AddressWidth( 6 ))
DATA_SC_IDX_48_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(DATA_SC_IDX_48_V_address0),
    .ce0(DATA_SC_IDX_48_V_ce0),
    .q0(DATA_SC_IDX_48_V_q0)
);

equalizer_symbol_iq_M_real_V #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
symbol_iq_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(symbol_iq_M_real_V_address0),
    .ce0(symbol_iq_M_real_V_ce0),
    .we0(symbol_iq_M_real_V_we0),
    .d0(grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_real_V_d0),
    .q0(symbol_iq_M_real_V_q0)
);

equalizer_symbol_iq_M_real_V #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
symbol_iq_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(symbol_iq_M_imag_V_address0),
    .ce0(symbol_iq_M_imag_V_ce0),
    .we0(symbol_iq_M_imag_V_we0),
    .d0(grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_imag_V_d0),
    .q0(symbol_iq_M_imag_V_q0)
);

equalizer_sym_phase_V #(
    .DataWidth( 18 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
sym_phase_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sym_phase_V_address0),
    .ce0(sym_phase_V_ce0),
    .we0(sym_phase_V_we0),
    .d0(sym_phase_V_d0),
    .q0(sym_phase_V_q0)
);

equalizer_lvpe_correction grp_lvpe_correction_fu_290(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_lvpe_correction_fu_290_ap_start),
    .ap_done(grp_lvpe_correction_fu_290_ap_done),
    .ap_idle(grp_lvpe_correction_fu_290_ap_idle),
    .ap_ready(grp_lvpe_correction_fu_290_ap_ready),
    .sym_phase_address0(grp_lvpe_correction_fu_290_sym_phase_address0),
    .sym_phase_ce0(grp_lvpe_correction_fu_290_sym_phase_ce0),
    .sym_phase_we0(grp_lvpe_correction_fu_290_sym_phase_we0),
    .sym_phase_d0(grp_lvpe_correction_fu_290_sym_phase_d0),
    .cpe(sext_ln41_reg_913),
    .prev_PEG(prev_PEG_V_load_reg_902)
);

equalizer_equalizer_Pipeline_lts_pilot grp_equalizer_Pipeline_lts_pilot_fu_307(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_equalizer_Pipeline_lts_pilot_fu_307_ap_start),
    .ap_done(grp_equalizer_Pipeline_lts_pilot_fu_307_ap_done),
    .ap_idle(grp_equalizer_Pipeline_lts_pilot_fu_307_ap_idle),
    .ap_ready(grp_equalizer_Pipeline_lts_pilot_fu_307_ap_ready),
    .new_lts_Addr_A(grp_equalizer_Pipeline_lts_pilot_fu_307_new_lts_Addr_A),
    .new_lts_EN_A(grp_equalizer_Pipeline_lts_pilot_fu_307_new_lts_EN_A),
    .new_lts_WEN_A(grp_equalizer_Pipeline_lts_pilot_fu_307_new_lts_WEN_A),
    .new_lts_Din_A(grp_equalizer_Pipeline_lts_pilot_fu_307_new_lts_Din_A),
    .new_lts_Dout_A(new_lts_Dout_A),
    .lts_pilot_M_imag_V_3_024_out(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_3_024_out),
    .lts_pilot_M_imag_V_3_024_out_ap_vld(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_3_024_out_ap_vld),
    .lts_pilot_M_imag_V_2_023_out(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_2_023_out),
    .lts_pilot_M_imag_V_2_023_out_ap_vld(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_2_023_out_ap_vld),
    .lts_pilot_M_imag_V_1_022_out(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_1_022_out),
    .lts_pilot_M_imag_V_1_022_out_ap_vld(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_1_022_out_ap_vld),
    .lts_pilot_M_imag_V_0_021_out(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_0_021_out),
    .lts_pilot_M_imag_V_0_021_out_ap_vld(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_0_021_out_ap_vld),
    .lts_pilot_M_real_V_3_020_out(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_3_020_out),
    .lts_pilot_M_real_V_3_020_out_ap_vld(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_3_020_out_ap_vld),
    .lts_pilot_M_real_V_2_019_out(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_2_019_out),
    .lts_pilot_M_real_V_2_019_out_ap_vld(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_2_019_out_ap_vld),
    .lts_pilot_M_real_V_1_018_out(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_1_018_out),
    .lts_pilot_M_real_V_1_018_out_ap_vld(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_1_018_out_ap_vld),
    .lts_pilot_M_real_V_0_017_out(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_0_017_out),
    .lts_pilot_M_real_V_0_017_out_ap_vld(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_0_017_out_ap_vld)
);

equalizer_equalizer_Pipeline_symbol_iq grp_equalizer_Pipeline_symbol_iq_fu_321(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_equalizer_Pipeline_symbol_iq_fu_321_ap_start),
    .ap_done(grp_equalizer_Pipeline_symbol_iq_fu_321_ap_done),
    .ap_idle(grp_equalizer_Pipeline_symbol_iq_fu_321_ap_idle),
    .ap_ready(grp_equalizer_Pipeline_symbol_iq_fu_321_ap_ready),
    .sample_in_V_dout(sample_in_V_dout),
    .sample_in_V_empty_n(sample_in_V_empty_n),
    .sample_in_V_read(grp_equalizer_Pipeline_symbol_iq_fu_321_sample_in_V_read),
    .symbol_iq_M_real_V_address0(grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_real_V_address0),
    .symbol_iq_M_real_V_ce0(grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_real_V_ce0),
    .symbol_iq_M_real_V_we0(grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_real_V_we0),
    .symbol_iq_M_real_V_d0(grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_real_V_d0),
    .symbol_iq_M_imag_V_address0(grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_imag_V_address0),
    .symbol_iq_M_imag_V_ce0(grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_imag_V_ce0),
    .symbol_iq_M_imag_V_we0(grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_imag_V_we0),
    .symbol_iq_M_imag_V_d0(grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_imag_V_d0)
);

equalizer_cpe_estimate grp_cpe_estimate_fu_329(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cpe_estimate_fu_329_ap_start),
    .ap_done(grp_cpe_estimate_fu_329_ap_done),
    .ap_idle(grp_cpe_estimate_fu_329_ap_idle),
    .ap_ready(grp_cpe_estimate_fu_329_ap_ready),
    .sample_in_M_real_0_0_0_address0(grp_cpe_estimate_fu_329_sample_in_M_real_0_0_0_address0),
    .sample_in_M_real_0_0_0_ce0(grp_cpe_estimate_fu_329_sample_in_M_real_0_0_0_ce0),
    .sample_in_M_real_0_0_0_q0(symbol_iq_M_real_V_q0),
    .sample_in_M_imag_0_0_0_address0(grp_cpe_estimate_fu_329_sample_in_M_imag_0_0_0_address0),
    .sample_in_M_imag_0_0_0_ce0(grp_cpe_estimate_fu_329_sample_in_M_imag_0_0_0_ce0),
    .sample_in_M_imag_0_0_0_q0(symbol_iq_M_imag_V_q0),
    .p_read(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_0_017_out),
    .p_read1(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_1_018_out),
    .p_read2(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_2_019_out),
    .p_read3(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_3_020_out),
    .p_read4(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_0_021_out),
    .p_read5(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_1_022_out),
    .p_read6(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_2_023_out),
    .p_read7(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_3_024_out),
    .p_read8(current_polarity_V_0_0_reg_279),
    .p_read9(current_polarity_V_1_reg_896),
    .p_read10(current_polarity_V_2_0_reg_258),
    .p_read11(current_polarity_V_3_0_reg_247),
    .atan_lut_V_address0(grp_cpe_estimate_fu_329_atan_lut_V_address0),
    .atan_lut_V_ce0(grp_cpe_estimate_fu_329_atan_lut_V_ce0),
    .atan_lut_V_q0(atan_lut_V_q0),
    .ap_return(grp_cpe_estimate_fu_329_ap_return)
);

equalizer_equalizer_Pipeline_lvpe_est grp_equalizer_Pipeline_lvpe_est_fu_352(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_equalizer_Pipeline_lvpe_est_fu_352_ap_start),
    .ap_done(grp_equalizer_Pipeline_lvpe_est_fu_352_ap_done),
    .ap_idle(grp_equalizer_Pipeline_lvpe_est_fu_352_ap_idle),
    .ap_ready(grp_equalizer_Pipeline_lvpe_est_fu_352_ap_ready),
    .sym_phase_V_address0(grp_equalizer_Pipeline_lvpe_est_fu_352_sym_phase_V_address0),
    .sym_phase_V_ce0(grp_equalizer_Pipeline_lvpe_est_fu_352_sym_phase_V_ce0),
    .sym_phase_V_q0(sym_phase_V_q0),
    .symbol_iq_M_real_V_address0(grp_equalizer_Pipeline_lvpe_est_fu_352_symbol_iq_M_real_V_address0),
    .symbol_iq_M_real_V_ce0(grp_equalizer_Pipeline_lvpe_est_fu_352_symbol_iq_M_real_V_ce0),
    .symbol_iq_M_real_V_q0(symbol_iq_M_real_V_q0),
    .symbol_iq_M_imag_V_address0(grp_equalizer_Pipeline_lvpe_est_fu_352_symbol_iq_M_imag_V_address0),
    .symbol_iq_M_imag_V_ce0(grp_equalizer_Pipeline_lvpe_est_fu_352_symbol_iq_M_imag_V_ce0),
    .symbol_iq_M_imag_V_q0(symbol_iq_M_imag_V_q0),
    .current_polarity_V_0_0(current_polarity_V_0_0_reg_279),
    .current_polarity_V_1(current_polarity_V_1_reg_896),
    .current_polarity_V_2_0(current_polarity_V_2_0_reg_258),
    .current_polarity_V_3_0(current_polarity_V_3_0_reg_247),
    .lts_pilot_M_real_V_0_017_reload(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_0_017_out),
    .lts_pilot_M_real_V_1_018_reload(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_1_018_out),
    .lts_pilot_M_real_V_2_019_reload(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_2_019_out),
    .lts_pilot_M_real_V_3_020_reload(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_real_V_3_020_out),
    .lts_pilot_M_imag_V_0_021_reload(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_0_021_out),
    .lts_pilot_M_imag_V_1_022_reload(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_1_022_out),
    .lts_pilot_M_imag_V_2_023_reload(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_2_023_out),
    .lts_pilot_M_imag_V_3_024_reload(grp_equalizer_Pipeline_lts_pilot_fu_307_lts_pilot_M_imag_V_3_024_out),
    .Sxy_V_1_out(grp_equalizer_Pipeline_lvpe_est_fu_352_Sxy_V_1_out),
    .Sxy_V_1_out_ap_vld(grp_equalizer_Pipeline_lvpe_est_fu_352_Sxy_V_1_out_ap_vld),
    .atan_lut_V_address0(grp_equalizer_Pipeline_lvpe_est_fu_352_atan_lut_V_address0),
    .atan_lut_V_ce0(grp_equalizer_Pipeline_lvpe_est_fu_352_atan_lut_V_ce0),
    .atan_lut_V_q0(atan_lut_V_q0),
    .grp_rotate_fu_947_p_din1(grp_equalizer_Pipeline_lvpe_est_fu_352_grp_rotate_fu_947_p_din1),
    .grp_rotate_fu_947_p_din2(grp_equalizer_Pipeline_lvpe_est_fu_352_grp_rotate_fu_947_p_din2),
    .grp_rotate_fu_947_p_din3(grp_equalizer_Pipeline_lvpe_est_fu_352_grp_rotate_fu_947_p_din3),
    .grp_rotate_fu_947_p_dout0_0(grp_rotate_fu_947_ap_return_0),
    .grp_rotate_fu_947_p_dout0_1(grp_rotate_fu_947_ap_return_1),
    .grp_rotate_fu_947_p_ce(grp_equalizer_Pipeline_lvpe_est_fu_352_grp_rotate_fu_947_p_ce),
    .grp_rotate_fu_947_p_start(grp_equalizer_Pipeline_lvpe_est_fu_352_grp_rotate_fu_947_p_start),
    .grp_rotate_fu_947_p_ready(grp_rotate_fu_947_ap_ready),
    .grp_rotate_fu_947_p_done(grp_rotate_fu_947_ap_done),
    .grp_rotate_fu_947_p_idle(grp_rotate_fu_947_ap_idle)
);

equalizer_equalizer_Pipeline_lvpe_corr grp_equalizer_Pipeline_lvpe_corr_fu_381(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_equalizer_Pipeline_lvpe_corr_fu_381_ap_start),
    .ap_done(grp_equalizer_Pipeline_lvpe_corr_fu_381_ap_done),
    .ap_idle(grp_equalizer_Pipeline_lvpe_corr_fu_381_ap_idle),
    .ap_ready(grp_equalizer_Pipeline_lvpe_corr_fu_381_ap_ready),
    .select_ln3(select_ln3_reg_877),
    .ht(ht),
    .sext_ln1543(grp_equalizer_Pipeline_lvpe_est_fu_352_Sxy_V_1_out),
    .trunc_ln3(trunc_ln70_reg_918),
    .sext_ln70(cpe_V_reg_908),
    .sym_phase_V_address0(grp_equalizer_Pipeline_lvpe_corr_fu_381_sym_phase_V_address0),
    .sym_phase_V_ce0(grp_equalizer_Pipeline_lvpe_corr_fu_381_sym_phase_V_ce0),
    .sym_phase_V_we0(grp_equalizer_Pipeline_lvpe_corr_fu_381_sym_phase_V_we0),
    .sym_phase_V_d0(grp_equalizer_Pipeline_lvpe_corr_fu_381_sym_phase_V_d0),
    .DATA_SC_IDX_52_V_address0(grp_equalizer_Pipeline_lvpe_corr_fu_381_DATA_SC_IDX_52_V_address0),
    .DATA_SC_IDX_52_V_ce0(grp_equalizer_Pipeline_lvpe_corr_fu_381_DATA_SC_IDX_52_V_ce0),
    .DATA_SC_IDX_52_V_q0(DATA_SC_IDX_52_V_q0),
    .DATA_SC_IDX_48_V_address0(grp_equalizer_Pipeline_lvpe_corr_fu_381_DATA_SC_IDX_48_V_address0),
    .DATA_SC_IDX_48_V_ce0(grp_equalizer_Pipeline_lvpe_corr_fu_381_DATA_SC_IDX_48_V_ce0),
    .DATA_SC_IDX_48_V_q0(DATA_SC_IDX_48_V_q0),
    .grp_fu_955_p_din0(grp_equalizer_Pipeline_lvpe_corr_fu_381_grp_fu_955_p_din0),
    .grp_fu_955_p_din1(grp_equalizer_Pipeline_lvpe_corr_fu_381_grp_fu_955_p_din1),
    .grp_fu_955_p_dout0(grp_fu_955_p2),
    .grp_fu_955_p_ce(grp_equalizer_Pipeline_lvpe_corr_fu_381_grp_fu_955_p_ce)
);

equalizer_equalizer_Pipeline_eq_per_sym grp_equalizer_Pipeline_eq_per_sym_fu_395(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_equalizer_Pipeline_eq_per_sym_fu_395_ap_start),
    .ap_done(grp_equalizer_Pipeline_eq_per_sym_fu_395_ap_done),
    .ap_idle(grp_equalizer_Pipeline_eq_per_sym_fu_395_ap_idle),
    .ap_ready(grp_equalizer_Pipeline_eq_per_sym_fu_395_ap_ready),
    .sample_out_V_din(grp_equalizer_Pipeline_eq_per_sym_fu_395_sample_out_V_din),
    .sample_out_V_full_n(sample_out_V_full_n),
    .sample_out_V_write(grp_equalizer_Pipeline_eq_per_sym_fu_395_sample_out_V_write),
    .select_ln3(select_ln3_reg_877),
    .ht(ht),
    .sym_phase_V_address0(grp_equalizer_Pipeline_eq_per_sym_fu_395_sym_phase_V_address0),
    .sym_phase_V_ce0(grp_equalizer_Pipeline_eq_per_sym_fu_395_sym_phase_V_ce0),
    .sym_phase_V_q0(sym_phase_V_q0),
    .symbol_iq_M_real_V_address0(grp_equalizer_Pipeline_eq_per_sym_fu_395_symbol_iq_M_real_V_address0),
    .symbol_iq_M_real_V_ce0(grp_equalizer_Pipeline_eq_per_sym_fu_395_symbol_iq_M_real_V_ce0),
    .symbol_iq_M_real_V_q0(symbol_iq_M_real_V_q0),
    .symbol_iq_M_imag_V_address0(grp_equalizer_Pipeline_eq_per_sym_fu_395_symbol_iq_M_imag_V_address0),
    .symbol_iq_M_imag_V_ce0(grp_equalizer_Pipeline_eq_per_sym_fu_395_symbol_iq_M_imag_V_ce0),
    .symbol_iq_M_imag_V_q0(symbol_iq_M_imag_V_q0),
    .new_lts_Addr_A(grp_equalizer_Pipeline_eq_per_sym_fu_395_new_lts_Addr_A),
    .new_lts_EN_A(grp_equalizer_Pipeline_eq_per_sym_fu_395_new_lts_EN_A),
    .new_lts_WEN_A(grp_equalizer_Pipeline_eq_per_sym_fu_395_new_lts_WEN_A),
    .new_lts_Din_A(grp_equalizer_Pipeline_eq_per_sym_fu_395_new_lts_Din_A),
    .new_lts_Dout_A(new_lts_Dout_A),
    .DATA_SC_IDX_52_V_address0(grp_equalizer_Pipeline_eq_per_sym_fu_395_DATA_SC_IDX_52_V_address0),
    .DATA_SC_IDX_52_V_ce0(grp_equalizer_Pipeline_eq_per_sym_fu_395_DATA_SC_IDX_52_V_ce0),
    .DATA_SC_IDX_52_V_q0(DATA_SC_IDX_52_V_q0),
    .DATA_SC_IDX_48_V_address0(grp_equalizer_Pipeline_eq_per_sym_fu_395_DATA_SC_IDX_48_V_address0),
    .DATA_SC_IDX_48_V_ce0(grp_equalizer_Pipeline_eq_per_sym_fu_395_DATA_SC_IDX_48_V_ce0),
    .DATA_SC_IDX_48_V_q0(DATA_SC_IDX_48_V_q0),
    .grp_rotate_fu_947_p_din1(grp_equalizer_Pipeline_eq_per_sym_fu_395_grp_rotate_fu_947_p_din1),
    .grp_rotate_fu_947_p_din2(grp_equalizer_Pipeline_eq_per_sym_fu_395_grp_rotate_fu_947_p_din2),
    .grp_rotate_fu_947_p_din3(grp_equalizer_Pipeline_eq_per_sym_fu_395_grp_rotate_fu_947_p_din3),
    .grp_rotate_fu_947_p_dout0_0(grp_rotate_fu_947_ap_return_0),
    .grp_rotate_fu_947_p_dout0_1(grp_rotate_fu_947_ap_return_1),
    .grp_rotate_fu_947_p_ce(grp_equalizer_Pipeline_eq_per_sym_fu_395_grp_rotate_fu_947_p_ce),
    .grp_rotate_fu_947_p_start(grp_equalizer_Pipeline_eq_per_sym_fu_395_grp_rotate_fu_947_p_start),
    .grp_rotate_fu_947_p_ready(grp_rotate_fu_947_ap_ready),
    .grp_rotate_fu_947_p_done(grp_rotate_fu_947_ap_done),
    .grp_rotate_fu_947_p_idle(grp_rotate_fu_947_ap_idle)
);

equalizer_rotate grp_rotate_fu_947(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_rotate_fu_947_ap_start),
    .ap_done(grp_rotate_fu_947_ap_done),
    .ap_idle(grp_rotate_fu_947_ap_idle),
    .ap_ready(grp_rotate_fu_947_ap_ready),
    .ap_ce(grp_rotate_fu_947_ap_ce),
    .phase(grp_rotate_fu_947_phase),
    .in_iq_M_real(grp_rotate_fu_947_in_iq_M_real),
    .in_iq_M_imag(grp_rotate_fu_947_in_iq_M_imag),
    .ap_return_0(grp_rotate_fu_947_ap_return_0),
    .ap_return_1(grp_rotate_fu_947_ap_return_1)
);

equalizer_mux_42_1_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
mux_42_1_1_1_x_U145(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd1),
    .din4(lhs_V_fu_519_p5),
    .dout(lhs_V_fu_519_p6)
);

equalizer_mux_42_1_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
mux_42_1_1_1_x_U146(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd1),
    .din4(lhs_V_1_fu_540_p5),
    .dout(lhs_V_1_fu_540_p6)
);

equalizer_mux_42_1_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
mux_42_1_1_1_x_U147(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd1),
    .din4(ht_pol_nr_V),
    .dout(lhs_V_2_fu_555_p6)
);

equalizer_mux_42_1_1_1_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 1 ))
mux_42_1_1_1_x_U148(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd1),
    .din4(lhs_V_3_fu_576_p5),
    .dout(lhs_V_3_fu_576_p6)
);

equalizer_mul_24s_26ns_50_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 50 ))
mul_24s_26ns_50_1_1_U149(
    .din0(r_fu_652_p3),
    .din1(mul_ln1543_1_fu_664_p1),
    .dout(mul_ln1543_1_fu_664_p2)
);

equalizer_mul_26s_28ns_52_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 28 ),
    .dout_WIDTH( 52 ))
mul_26s_28ns_52_3_1_U150(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_equalizer_Pipeline_lvpe_corr_fu_381_grp_fu_955_p_din0),
    .din1(grp_equalizer_Pipeline_lvpe_corr_fu_381_grp_fu_955_p_din1),
    .ce(grp_fu_955_ce),
    .dout(grp_fu_955_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cpe_estimate_fu_329_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_cpe_estimate_fu_329_ap_start_reg <= 1'b1;
        end else if ((grp_cpe_estimate_fu_329_ap_ready == 1'b1)) begin
            grp_cpe_estimate_fu_329_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_equalizer_Pipeline_eq_per_sym_fu_395_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_equalizer_Pipeline_eq_per_sym_fu_395_ap_start_reg <= 1'b1;
        end else if ((grp_equalizer_Pipeline_eq_per_sym_fu_395_ap_ready == 1'b1)) begin
            grp_equalizer_Pipeline_eq_per_sym_fu_395_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_equalizer_Pipeline_lts_pilot_fu_307_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_equalizer_Pipeline_lts_pilot_fu_307_ap_start_reg <= 1'b1;
        end else if ((grp_equalizer_Pipeline_lts_pilot_fu_307_ap_ready == 1'b1)) begin
            grp_equalizer_Pipeline_lts_pilot_fu_307_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_equalizer_Pipeline_lvpe_corr_fu_381_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_equalizer_Pipeline_lvpe_corr_fu_381_ap_start_reg <= 1'b1;
        end else if ((grp_equalizer_Pipeline_lvpe_corr_fu_381_ap_ready == 1'b1)) begin
            grp_equalizer_Pipeline_lvpe_corr_fu_381_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_equalizer_Pipeline_lvpe_est_fu_352_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_equalizer_Pipeline_lvpe_est_fu_352_ap_start_reg <= 1'b1;
        end else if ((grp_equalizer_Pipeline_lvpe_est_fu_352_ap_ready == 1'b1)) begin
            grp_equalizer_Pipeline_lvpe_est_fu_352_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_equalizer_Pipeline_symbol_iq_fu_321_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln31_fu_481_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
            grp_equalizer_Pipeline_symbol_iq_fu_321_ap_start_reg <= 1'b1;
        end else if ((grp_equalizer_Pipeline_symbol_iq_fu_321_ap_ready == 1'b1)) begin
            grp_equalizer_Pipeline_symbol_iq_fu_321_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_lvpe_correction_fu_290_ap_start_reg <= 1'b0;
    end else begin
        if (((grp_cpe_estimate_fu_329_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
            grp_lvpe_correction_fu_290_ap_start_reg <= 1'b1;
        end else if ((grp_lvpe_correction_fu_290_ap_ready == 1'b1)) begin
            grp_lvpe_correction_fu_290_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ht_pol_nr_V <= 2'd0;
    end else begin
        if (((ht_read_read_fu_222_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
            ht_pol_nr_V <= fourth_fu_513_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        if ((ht_read_read_fu_222_p2 == 1'd0)) begin
            current_polarity_V_0_0_reg_279 <= POLARITY_V_q0;
        end else if ((ht_read_read_fu_222_p2 == 1'd1)) begin
            current_polarity_V_0_0_reg_279 <= ret_fu_533_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        if ((ht_read_read_fu_222_p2 == 1'd0)) begin
            current_polarity_V_2_0_reg_258 <= POLARITY_V_q0;
        end else if ((ht_read_read_fu_222_p2 == 1'd1)) begin
            current_polarity_V_2_0_reg_258 <= ret_17_fu_569_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        if ((ht_read_read_fu_222_p2 == 1'd0)) begin
            current_polarity_V_3_0_reg_247 <= POLARITY_V_q0;
        end else if ((ht_read_read_fu_222_p2 == 1'd1)) begin
            current_polarity_V_3_0_reg_247 <= ret_18_fu_590_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_V_fu_160 <= 12'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        i_V_fu_160 <= i_V_6_reg_886;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        pol_nr_V_fu_164 <= select_ln3_1_fu_457_p3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        pol_nr_V_fu_164 <= select_ln23_fu_622_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        prev_PEG_V_fu_156 <= prev_PEG;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        prev_PEG_V_fu_156 <= prev_PEG_V_1_fu_757_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cpe_V_reg_908 <= grp_cpe_estimate_fu_329_ap_return;
        prev_PEG_V_load_reg_902 <= prev_PEG_V_fu_156;
        sext_ln41_reg_913 <= sext_ln41_fu_639_p1;
        trunc_ln70_reg_918 <= trunc_ln70_fu_644_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        current_polarity_V_1_reg_896 <= current_polarity_V_1_fu_603_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_V_6_reg_886 <= i_V_6_fu_486_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        select_ln3_reg_877[2] <= select_ln3_fu_465_p3[2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state13) & (tmp_reg_931 == 1'd1))) begin
        tmp_15_reg_942 <= {{sub_ln1543_fu_692_p2[48:34]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        tmp_16_reg_937 <= {{mul_ln1543_1_fu_664_p2[49:34]}};
        tmp_reg_931 <= grp_equalizer_Pipeline_lvpe_est_fu_352_Sxy_V_1_out[32'd18];
        trunc_ln1543_reg_926 <= trunc_ln1543_fu_670_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        DATA_SC_IDX_48_V_address0 = grp_equalizer_Pipeline_eq_per_sym_fu_395_DATA_SC_IDX_48_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        DATA_SC_IDX_48_V_address0 = grp_equalizer_Pipeline_lvpe_corr_fu_381_DATA_SC_IDX_48_V_address0;
    end else begin
        DATA_SC_IDX_48_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        DATA_SC_IDX_48_V_ce0 = grp_equalizer_Pipeline_eq_per_sym_fu_395_DATA_SC_IDX_48_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        DATA_SC_IDX_48_V_ce0 = grp_equalizer_Pipeline_lvpe_corr_fu_381_DATA_SC_IDX_48_V_ce0;
    end else begin
        DATA_SC_IDX_48_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        DATA_SC_IDX_52_V_address0 = grp_equalizer_Pipeline_eq_per_sym_fu_395_DATA_SC_IDX_52_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        DATA_SC_IDX_52_V_address0 = grp_equalizer_Pipeline_lvpe_corr_fu_381_DATA_SC_IDX_52_V_address0;
    end else begin
        DATA_SC_IDX_52_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        DATA_SC_IDX_52_V_ce0 = grp_equalizer_Pipeline_eq_per_sym_fu_395_DATA_SC_IDX_52_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        DATA_SC_IDX_52_V_ce0 = grp_equalizer_Pipeline_lvpe_corr_fu_381_DATA_SC_IDX_52_V_ce0;
    end else begin
        DATA_SC_IDX_52_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        POLARITY_V_ce0 = 1'b1;
    end else begin
        POLARITY_V_ce0 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_equalizer_Pipeline_lvpe_est_fu_352_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_equalizer_Pipeline_lvpe_corr_fu_381_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_equalizer_Pipeline_eq_per_sym_fu_395_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_equalizer_Pipeline_lts_pilot_fu_307_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_equalizer_Pipeline_symbol_iq_fu_321_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_cpe_estimate_fu_329_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_lvpe_correction_fu_290_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_481_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        if ((ht_read_read_fu_222_p2 == 1'd0)) begin
            ap_phi_mux_p_pn_phi_fu_272_p4 = 1'd1;
        end else if ((ht_read_read_fu_222_p2 == 1'd1)) begin
            ap_phi_mux_p_pn_phi_fu_272_p4 = lhs_V_1_fu_540_p6;
        end else begin
            ap_phi_mux_p_pn_phi_fu_272_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_p_pn_phi_fu_272_p4 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_481_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        atan_lut_V_address0 = grp_equalizer_Pipeline_lvpe_est_fu_352_atan_lut_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        atan_lut_V_address0 = grp_cpe_estimate_fu_329_atan_lut_V_address0;
    end else begin
        atan_lut_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        atan_lut_V_ce0 = grp_equalizer_Pipeline_lvpe_est_fu_352_atan_lut_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        atan_lut_V_ce0 = grp_cpe_estimate_fu_329_atan_lut_V_ce0;
    end else begin
        atan_lut_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_fu_955_ce = grp_equalizer_Pipeline_lvpe_corr_fu_381_grp_fu_955_p_ce;
    end else begin
        grp_fu_955_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        grp_rotate_fu_947_ap_ce = grp_equalizer_Pipeline_eq_per_sym_fu_395_grp_rotate_fu_947_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        grp_rotate_fu_947_ap_ce = grp_equalizer_Pipeline_lvpe_est_fu_352_grp_rotate_fu_947_p_ce;
    end else begin
        grp_rotate_fu_947_ap_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        grp_rotate_fu_947_ap_start = grp_equalizer_Pipeline_eq_per_sym_fu_395_grp_rotate_fu_947_p_start;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        grp_rotate_fu_947_ap_start = grp_equalizer_Pipeline_lvpe_est_fu_352_grp_rotate_fu_947_p_start;
    end else begin
        grp_rotate_fu_947_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        grp_rotate_fu_947_in_iq_M_imag = grp_equalizer_Pipeline_eq_per_sym_fu_395_grp_rotate_fu_947_p_din3;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        grp_rotate_fu_947_in_iq_M_imag = grp_equalizer_Pipeline_lvpe_est_fu_352_grp_rotate_fu_947_p_din3;
    end else begin
        grp_rotate_fu_947_in_iq_M_imag = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        grp_rotate_fu_947_in_iq_M_real = grp_equalizer_Pipeline_eq_per_sym_fu_395_grp_rotate_fu_947_p_din2;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        grp_rotate_fu_947_in_iq_M_real = grp_equalizer_Pipeline_lvpe_est_fu_352_grp_rotate_fu_947_p_din2;
    end else begin
        grp_rotate_fu_947_in_iq_M_real = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14))) begin
        grp_rotate_fu_947_phase = grp_equalizer_Pipeline_eq_per_sym_fu_395_grp_rotate_fu_947_p_din1;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        grp_rotate_fu_947_phase = grp_equalizer_Pipeline_lvpe_est_fu_352_grp_rotate_fu_947_p_din1;
    end else begin
        grp_rotate_fu_947_phase = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        new_lts_Addr_A = grp_equalizer_Pipeline_eq_per_sym_fu_395_new_lts_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        new_lts_Addr_A = grp_equalizer_Pipeline_lts_pilot_fu_307_new_lts_Addr_A;
    end else begin
        new_lts_Addr_A = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        new_lts_EN_A = grp_equalizer_Pipeline_eq_per_sym_fu_395_new_lts_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        new_lts_EN_A = grp_equalizer_Pipeline_lts_pilot_fu_307_new_lts_EN_A;
    end else begin
        new_lts_EN_A = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        sample_in_V_read = grp_equalizer_Pipeline_symbol_iq_fu_321_sample_in_V_read;
    end else begin
        sample_in_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        sample_out_V_write = grp_equalizer_Pipeline_eq_per_sym_fu_395_sample_out_V_write;
    end else begin
        sample_out_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        sym_phase_V_address0 = grp_equalizer_Pipeline_eq_per_sym_fu_395_sym_phase_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        sym_phase_V_address0 = grp_equalizer_Pipeline_lvpe_corr_fu_381_sym_phase_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        sym_phase_V_address0 = grp_equalizer_Pipeline_lvpe_est_fu_352_sym_phase_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        sym_phase_V_address0 = grp_lvpe_correction_fu_290_sym_phase_address0;
    end else begin
        sym_phase_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        sym_phase_V_ce0 = grp_equalizer_Pipeline_eq_per_sym_fu_395_sym_phase_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        sym_phase_V_ce0 = grp_equalizer_Pipeline_lvpe_corr_fu_381_sym_phase_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        sym_phase_V_ce0 = grp_equalizer_Pipeline_lvpe_est_fu_352_sym_phase_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        sym_phase_V_ce0 = grp_lvpe_correction_fu_290_sym_phase_ce0;
    end else begin
        sym_phase_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        sym_phase_V_d0 = grp_equalizer_Pipeline_lvpe_corr_fu_381_sym_phase_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        sym_phase_V_d0 = grp_lvpe_correction_fu_290_sym_phase_d0;
    end else begin
        sym_phase_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        sym_phase_V_we0 = grp_equalizer_Pipeline_lvpe_corr_fu_381_sym_phase_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        sym_phase_V_we0 = grp_lvpe_correction_fu_290_sym_phase_we0;
    end else begin
        sym_phase_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        symbol_iq_M_imag_V_address0 = grp_equalizer_Pipeline_eq_per_sym_fu_395_symbol_iq_M_imag_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        symbol_iq_M_imag_V_address0 = grp_equalizer_Pipeline_lvpe_est_fu_352_symbol_iq_M_imag_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        symbol_iq_M_imag_V_address0 = grp_cpe_estimate_fu_329_sample_in_M_imag_0_0_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        symbol_iq_M_imag_V_address0 = grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_imag_V_address0;
    end else begin
        symbol_iq_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        symbol_iq_M_imag_V_ce0 = grp_equalizer_Pipeline_eq_per_sym_fu_395_symbol_iq_M_imag_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        symbol_iq_M_imag_V_ce0 = grp_equalizer_Pipeline_lvpe_est_fu_352_symbol_iq_M_imag_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        symbol_iq_M_imag_V_ce0 = grp_cpe_estimate_fu_329_sample_in_M_imag_0_0_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        symbol_iq_M_imag_V_ce0 = grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_imag_V_ce0;
    end else begin
        symbol_iq_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        symbol_iq_M_imag_V_we0 = grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_imag_V_we0;
    end else begin
        symbol_iq_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        symbol_iq_M_real_V_address0 = grp_equalizer_Pipeline_eq_per_sym_fu_395_symbol_iq_M_real_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        symbol_iq_M_real_V_address0 = grp_equalizer_Pipeline_lvpe_est_fu_352_symbol_iq_M_real_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        symbol_iq_M_real_V_address0 = grp_cpe_estimate_fu_329_sample_in_M_real_0_0_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        symbol_iq_M_real_V_address0 = grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_real_V_address0;
    end else begin
        symbol_iq_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        symbol_iq_M_real_V_ce0 = grp_equalizer_Pipeline_eq_per_sym_fu_395_symbol_iq_M_real_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        symbol_iq_M_real_V_ce0 = grp_equalizer_Pipeline_lvpe_est_fu_352_symbol_iq_M_real_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        symbol_iq_M_real_V_ce0 = grp_cpe_estimate_fu_329_sample_in_M_real_0_0_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        symbol_iq_M_real_V_ce0 = grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_real_V_ce0;
    end else begin
        symbol_iq_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        symbol_iq_M_real_V_we0 = grp_equalizer_Pipeline_symbol_iq_fu_321_symbol_iq_M_real_V_we0;
    end else begin
        symbol_iq_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_equalizer_Pipeline_lts_pilot_fu_307_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln31_fu_481_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((grp_equalizer_Pipeline_symbol_iq_fu_321_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_cpe_estimate_fu_329_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_lvpe_correction_fu_290_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_equalizer_Pipeline_lvpe_est_fu_352_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_equalizer_Pipeline_lvpe_corr_fu_381_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_equalizer_Pipeline_eq_per_sym_fu_395_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign POLARITY_V_address0 = zext_ln573_1_fu_492_p1;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return = prev_PEG_V_fu_156;

assign current_polarity_V_1_fu_603_p2 = (ap_phi_mux_p_pn_phi_fu_272_p4 ^ POLARITY_V_q0);

assign fourth_fu_513_p2 = (ht_pol_nr_V + 2'd1);

assign grp_cpe_estimate_fu_329_ap_start = grp_cpe_estimate_fu_329_ap_start_reg;

assign grp_equalizer_Pipeline_eq_per_sym_fu_395_ap_start = grp_equalizer_Pipeline_eq_per_sym_fu_395_ap_start_reg;

assign grp_equalizer_Pipeline_lts_pilot_fu_307_ap_start = grp_equalizer_Pipeline_lts_pilot_fu_307_ap_start_reg;

assign grp_equalizer_Pipeline_lvpe_corr_fu_381_ap_start = grp_equalizer_Pipeline_lvpe_corr_fu_381_ap_start_reg;

assign grp_equalizer_Pipeline_lvpe_est_fu_352_ap_start = grp_equalizer_Pipeline_lvpe_est_fu_352_ap_start_reg;

assign grp_equalizer_Pipeline_symbol_iq_fu_321_ap_start = grp_equalizer_Pipeline_symbol_iq_fu_321_ap_start_reg;

assign grp_lvpe_correction_fu_290_ap_start = grp_lvpe_correction_fu_290_ap_start_reg;

assign ht_read_read_fu_222_p2 = ht;

assign i_V_6_fu_486_p2 = (i_V_fu_160 + 12'd1);

assign icmp_ln1049_fu_610_p2 = ((pol_nr_V_fu_164 == 7'd126) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_481_p2 = ((i_V_fu_160 == nof_ofdm_sym) ? 1'b1 : 1'b0);

assign lhs_V_1_fu_540_p5 = ($signed(ht_pol_nr_V) + $signed(2'd3));

assign lhs_V_3_fu_576_p5 = (ht_pol_nr_V + 2'd1);

assign lhs_V_fu_519_p5 = (ht_pol_nr_V ^ 2'd2);

assign mul_ln1543_1_fu_664_p1 = 50'd17530479;

assign new_lts_Clk_A = ap_clk;

assign new_lts_Din_A = 32'd0;

assign new_lts_Rst_A = ap_rst;

assign new_lts_WEN_A = 4'd0;

assign pol_nr_V_1_fu_616_p2 = (pol_nr_V_fu_164 + 7'd1);

assign prev_PEG_V_1_fu_757_p2 = ($signed(sext_ln1676_fu_753_p1) + $signed(prev_PEG_V_load_reg_902));

assign r_2_fu_746_p3 = ((tmp_reg_931[0:0] == 1'b1) ? tmp_s_fu_726_p4 : tmp_2_fu_736_p4);

assign r_fu_652_p3 = {{grp_equalizer_Pipeline_lvpe_est_fu_352_Sxy_V_1_out}, {5'd0}};

assign ret_17_fu_569_p2 = (lhs_V_2_fu_555_p6 ^ POLARITY_V_q0);

assign ret_18_fu_590_p2 = (lhs_V_3_fu_576_p6 ^ POLARITY_V_q0);

assign ret_fu_533_p2 = (lhs_V_fu_519_p6 ^ POLARITY_V_q0);

assign sample_out_V_din = grp_equalizer_Pipeline_eq_per_sym_fu_395_sample_out_V_din;

assign select_ln1543_fu_713_p3 = ((tmp_reg_931[0:0] == 1'b1) ? sext_ln1543_4_fu_707_p1 : sext_ln1543_5_fu_710_p1);

assign select_ln23_fu_622_p3 = ((icmp_ln1049_fu_610_p2[0:0] == 1'b1) ? 7'd0 : pol_nr_V_1_fu_616_p2);

assign select_ln3_1_fu_457_p3 = ((ht[0:0] == 1'b1) ? 7'd3 : 7'd0);

assign select_ln3_fu_465_p3 = ((ht[0:0] == 1'b1) ? 5'd20 : 5'd16);

assign sext_ln1543_4_fu_707_p1 = $signed(tmp_15_reg_942);

assign sext_ln1543_5_fu_710_p1 = $signed(tmp_16_reg_937);

assign sext_ln1676_fu_753_p1 = $signed(r_2_fu_746_p3);

assign sext_ln41_fu_639_p0 = grp_cpe_estimate_fu_329_ap_return;

assign sext_ln41_fu_639_p1 = sext_ln41_fu_639_p0;

assign sub_ln1543_1_fu_720_p2 = (24'd0 - select_ln1543_fu_713_p3);

assign sub_ln1543_fu_692_p2 = (49'd0 - trunc_ln1543_reg_926);

assign tmp_2_fu_736_p4 = {{select_ln1543_fu_713_p3[23:5]}};

assign tmp_s_fu_726_p4 = {{sub_ln1543_1_fu_720_p2[23:5]}};

assign trunc_ln1543_fu_670_p1 = mul_ln1543_1_fu_664_p2[48:0];

assign trunc_ln70_fu_644_p1 = prev_PEG_V_fu_156[17:0];

assign zext_ln573_1_fu_492_p1 = pol_nr_V_fu_164;

always @ (posedge ap_clk) begin
    select_ln3_reg_877[1:0] <= 2'b00;
    select_ln3_reg_877[4:3] <= 2'b10;
end

endmodule //equalizer
