// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ch_gain_cal_ch_gain_cal,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010i-clg225-1L,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=5,HLS_SYN_DSP=0,HLS_SYN_FF=1287,HLS_SYN_LUT=2273,HLS_VERSION=2021_1}" *)

module ch_gain_cal (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        lts_iq_fd_V_dout,
        lts_iq_fd_V_empty_n,
        lts_iq_fd_V_read,
        new_lts_Addr_A,
        new_lts_EN_A,
        new_lts_WEN_A,
        new_lts_Din_A,
        new_lts_Dout_A,
        new_lts_Clk_A,
        new_lts_Rst_A,
        smooth,
        ltf_type
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] lts_iq_fd_V_dout;
input   lts_iq_fd_V_empty_n;
output   lts_iq_fd_V_read;
output  [31:0] new_lts_Addr_A;
output   new_lts_EN_A;
output  [3:0] new_lts_WEN_A;
output  [31:0] new_lts_Din_A;
input  [31:0] new_lts_Dout_A;
output   new_lts_Clk_A;
output   new_lts_Rst_A;
input  [0:0] smooth;
input  [0:0] ltf_type;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg lts_iq_fd_V_read;
reg[31:0] new_lts_Addr_A;
reg new_lts_EN_A;
reg[3:0] new_lts_WEN_A;
reg[31:0] new_lts_Din_A;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] smooth_read_read_fu_90_p2;
wire   [3:0] len_V_fu_146_p3;
reg   [3:0] len_V_reg_178;
wire    ap_CS_fsm_state3;
wire   [9:0] arr1_fu_153_p3;
reg   [9:0] arr1_reg_183;
wire   [9:0] arr2_fu_160_p3;
reg   [9:0] arr2_reg_188;
wire    ap_CS_fsm_state7;
reg   [5:0] first_lts_M_real_V_address0;
reg    first_lts_M_real_V_ce0;
reg    first_lts_M_real_V_we0;
reg   [15:0] first_lts_M_real_V_d0;
wire   [15:0] first_lts_M_real_V_q0;
reg    first_lts_M_real_V_ce1;
wire   [15:0] first_lts_M_real_V_q1;
reg   [5:0] first_lts_M_imag_V_address0;
reg    first_lts_M_imag_V_ce0;
reg    first_lts_M_imag_V_we0;
reg   [15:0] first_lts_M_imag_V_d0;
wire   [15:0] first_lts_M_imag_V_q0;
reg    first_lts_M_imag_V_ce1;
wire   [15:0] first_lts_M_imag_V_q1;
reg   [5:0] avg_lts_M_real_V_address0;
reg    avg_lts_M_real_V_ce0;
reg    avg_lts_M_real_V_we0;
reg   [15:0] avg_lts_M_real_V_d0;
wire   [15:0] avg_lts_M_real_V_q0;
reg   [5:0] avg_lts_M_imag_V_address0;
reg    avg_lts_M_imag_V_ce0;
reg    avg_lts_M_imag_V_we0;
reg   [15:0] avg_lts_M_imag_V_d0;
wire   [15:0] avg_lts_M_imag_V_q0;
wire    grp_ch_gain_cal_Pipeline_l_lts_fu_96_ap_start;
wire    grp_ch_gain_cal_Pipeline_l_lts_fu_96_ap_done;
wire    grp_ch_gain_cal_Pipeline_l_lts_fu_96_ap_idle;
wire    grp_ch_gain_cal_Pipeline_l_lts_fu_96_ap_ready;
wire    grp_ch_gain_cal_Pipeline_l_lts_fu_96_lts_iq_fd_V_read;
wire   [5:0] grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_real_V_address0;
wire    grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_real_V_ce0;
wire    grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_real_V_we0;
wire   [15:0] grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_real_V_d0;
wire   [5:0] grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_real_V_address1;
wire    grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_real_V_ce1;
wire   [5:0] grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_imag_V_address0;
wire    grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_imag_V_ce0;
wire    grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_imag_V_we0;
wire   [15:0] grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_imag_V_d0;
wire   [5:0] grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_imag_V_address1;
wire    grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_imag_V_ce1;
wire   [5:0] grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_real_V_address0;
wire    grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_real_V_ce0;
wire    grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_real_V_we0;
wire   [15:0] grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_real_V_d0;
wire   [5:0] grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_imag_V_address0;
wire    grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_imag_V_ce0;
wire    grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_imag_V_we0;
wire   [15:0] grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_imag_V_d0;
wire    grp_ch_gain_cal_Pipeline_ht_lts_fu_108_ap_start;
wire    grp_ch_gain_cal_Pipeline_ht_lts_fu_108_ap_done;
wire    grp_ch_gain_cal_Pipeline_ht_lts_fu_108_ap_idle;
wire    grp_ch_gain_cal_Pipeline_ht_lts_fu_108_ap_ready;
wire    grp_ch_gain_cal_Pipeline_ht_lts_fu_108_lts_iq_fd_V_read;
wire   [5:0] grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_real_V_address0;
wire    grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_real_V_ce0;
wire    grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_real_V_we0;
wire   [15:0] grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_real_V_d0;
wire   [5:0] grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_imag_V_address0;
wire    grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_imag_V_ce0;
wire    grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_imag_V_we0;
wire   [15:0] grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_imag_V_d0;
wire    grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_ap_start;
wire    grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_ap_done;
wire    grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_ap_idle;
wire    grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_ap_ready;
wire   [5:0] grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_avg_lts_M_real_V_address0;
wire    grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_avg_lts_M_real_V_ce0;
wire   [5:0] grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_avg_lts_M_imag_V_address0;
wire    grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_avg_lts_M_imag_V_ce0;
wire   [31:0] grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_new_lts_Addr_A;
wire    grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_new_lts_EN_A;
wire   [3:0] grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_new_lts_WEN_A;
wire   [31:0] grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_new_lts_Din_A;
wire    grp_moving_avg_fu_126_ap_start;
wire    grp_moving_avg_fu_126_ap_done;
wire    grp_moving_avg_fu_126_ap_idle;
wire    grp_moving_avg_fu_126_ap_ready;
wire   [5:0] grp_moving_avg_fu_126_iq_samples_in_M_real_address0;
wire    grp_moving_avg_fu_126_iq_samples_in_M_real_ce0;
wire   [5:0] grp_moving_avg_fu_126_iq_samples_in_M_imag_address0;
wire    grp_moving_avg_fu_126_iq_samples_in_M_imag_ce0;
wire   [5:0] grp_moving_avg_fu_126_iq_samples_out_M_real_0_0_0_address0;
wire    grp_moving_avg_fu_126_iq_samples_out_M_real_0_0_0_ce0;
wire    grp_moving_avg_fu_126_iq_samples_out_M_real_0_0_0_we0;
wire   [15:0] grp_moving_avg_fu_126_iq_samples_out_M_real_0_0_0_d0;
wire   [5:0] grp_moving_avg_fu_126_iq_samples_out_M_imag_0_0_0_address0;
wire    grp_moving_avg_fu_126_iq_samples_out_M_imag_0_0_0_ce0;
wire    grp_moving_avg_fu_126_iq_samples_out_M_imag_0_0_0_we0;
wire   [15:0] grp_moving_avg_fu_126_iq_samples_out_M_imag_0_0_0_d0;
reg   [9:0] grp_moving_avg_fu_126_arr;
wire    grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_ap_start;
wire    grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_ap_done;
wire    grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_ap_idle;
wire    grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_ap_ready;
wire   [5:0] grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_first_lts_M_real_V_address0;
wire    grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_first_lts_M_real_V_ce0;
wire   [5:0] grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_first_lts_M_imag_V_address0;
wire    grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_first_lts_M_imag_V_ce0;
wire   [31:0] grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_new_lts_Addr_A;
wire    grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_new_lts_EN_A;
wire   [3:0] grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_new_lts_WEN_A;
wire   [31:0] grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_new_lts_Din_A;
reg    grp_ch_gain_cal_Pipeline_l_lts_fu_96_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_ch_gain_cal_Pipeline_ht_lts_fu_108_ap_start_reg;
reg    grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    grp_moving_avg_fu_126_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg    grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg    ap_block_state11_on_subcall_done;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_block_state3_on_subcall_done;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 grp_ch_gain_cal_Pipeline_l_lts_fu_96_ap_start_reg = 1'b0;
#0 grp_ch_gain_cal_Pipeline_ht_lts_fu_108_ap_start_reg = 1'b0;
#0 grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_ap_start_reg = 1'b0;
#0 grp_moving_avg_fu_126_ap_start_reg = 1'b0;
#0 grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_ap_start_reg = 1'b0;
end

ch_gain_cal_first_lts_M_real_V #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
first_lts_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(first_lts_M_real_V_address0),
    .ce0(first_lts_M_real_V_ce0),
    .we0(first_lts_M_real_V_we0),
    .d0(first_lts_M_real_V_d0),
    .q0(first_lts_M_real_V_q0),
    .address1(grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_real_V_address1),
    .ce1(first_lts_M_real_V_ce1),
    .q1(first_lts_M_real_V_q1)
);

ch_gain_cal_first_lts_M_real_V #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
first_lts_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(first_lts_M_imag_V_address0),
    .ce0(first_lts_M_imag_V_ce0),
    .we0(first_lts_M_imag_V_we0),
    .d0(first_lts_M_imag_V_d0),
    .q0(first_lts_M_imag_V_q0),
    .address1(grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_imag_V_address1),
    .ce1(first_lts_M_imag_V_ce1),
    .q1(first_lts_M_imag_V_q1)
);

ch_gain_cal_avg_lts_M_real_V #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
avg_lts_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(avg_lts_M_real_V_address0),
    .ce0(avg_lts_M_real_V_ce0),
    .we0(avg_lts_M_real_V_we0),
    .d0(avg_lts_M_real_V_d0),
    .q0(avg_lts_M_real_V_q0)
);

ch_gain_cal_avg_lts_M_real_V #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
avg_lts_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(avg_lts_M_imag_V_address0),
    .ce0(avg_lts_M_imag_V_ce0),
    .we0(avg_lts_M_imag_V_we0),
    .d0(avg_lts_M_imag_V_d0),
    .q0(avg_lts_M_imag_V_q0)
);

ch_gain_cal_ch_gain_cal_Pipeline_l_lts grp_ch_gain_cal_Pipeline_l_lts_fu_96(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ch_gain_cal_Pipeline_l_lts_fu_96_ap_start),
    .ap_done(grp_ch_gain_cal_Pipeline_l_lts_fu_96_ap_done),
    .ap_idle(grp_ch_gain_cal_Pipeline_l_lts_fu_96_ap_idle),
    .ap_ready(grp_ch_gain_cal_Pipeline_l_lts_fu_96_ap_ready),
    .lts_iq_fd_V_dout(lts_iq_fd_V_dout),
    .lts_iq_fd_V_empty_n(lts_iq_fd_V_empty_n),
    .lts_iq_fd_V_read(grp_ch_gain_cal_Pipeline_l_lts_fu_96_lts_iq_fd_V_read),
    .first_lts_M_real_V_address0(grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_real_V_address0),
    .first_lts_M_real_V_ce0(grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_real_V_ce0),
    .first_lts_M_real_V_we0(grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_real_V_we0),
    .first_lts_M_real_V_d0(grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_real_V_d0),
    .first_lts_M_real_V_address1(grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_real_V_address1),
    .first_lts_M_real_V_ce1(grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_real_V_ce1),
    .first_lts_M_real_V_q1(first_lts_M_real_V_q1),
    .first_lts_M_imag_V_address0(grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_imag_V_address0),
    .first_lts_M_imag_V_ce0(grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_imag_V_ce0),
    .first_lts_M_imag_V_we0(grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_imag_V_we0),
    .first_lts_M_imag_V_d0(grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_imag_V_d0),
    .first_lts_M_imag_V_address1(grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_imag_V_address1),
    .first_lts_M_imag_V_ce1(grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_imag_V_ce1),
    .first_lts_M_imag_V_q1(first_lts_M_imag_V_q1),
    .avg_lts_M_real_V_address0(grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_real_V_address0),
    .avg_lts_M_real_V_ce0(grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_real_V_ce0),
    .avg_lts_M_real_V_we0(grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_real_V_we0),
    .avg_lts_M_real_V_d0(grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_real_V_d0),
    .avg_lts_M_imag_V_address0(grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_imag_V_address0),
    .avg_lts_M_imag_V_ce0(grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_imag_V_ce0),
    .avg_lts_M_imag_V_we0(grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_imag_V_we0),
    .avg_lts_M_imag_V_d0(grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_imag_V_d0)
);

ch_gain_cal_ch_gain_cal_Pipeline_ht_lts grp_ch_gain_cal_Pipeline_ht_lts_fu_108(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ch_gain_cal_Pipeline_ht_lts_fu_108_ap_start),
    .ap_done(grp_ch_gain_cal_Pipeline_ht_lts_fu_108_ap_done),
    .ap_idle(grp_ch_gain_cal_Pipeline_ht_lts_fu_108_ap_idle),
    .ap_ready(grp_ch_gain_cal_Pipeline_ht_lts_fu_108_ap_ready),
    .lts_iq_fd_V_dout(lts_iq_fd_V_dout),
    .lts_iq_fd_V_empty_n(lts_iq_fd_V_empty_n),
    .lts_iq_fd_V_read(grp_ch_gain_cal_Pipeline_ht_lts_fu_108_lts_iq_fd_V_read),
    .avg_lts_M_real_V_address0(grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_real_V_address0),
    .avg_lts_M_real_V_ce0(grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_real_V_ce0),
    .avg_lts_M_real_V_we0(grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_real_V_we0),
    .avg_lts_M_real_V_d0(grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_real_V_d0),
    .avg_lts_M_imag_V_address0(grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_imag_V_address0),
    .avg_lts_M_imag_V_ce0(grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_imag_V_ce0),
    .avg_lts_M_imag_V_we0(grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_imag_V_we0),
    .avg_lts_M_imag_V_d0(grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_imag_V_d0)
);

ch_gain_cal_ch_gain_cal_Pipeline_new_lts_out grp_ch_gain_cal_Pipeline_new_lts_out_fu_118(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_ap_start),
    .ap_done(grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_ap_done),
    .ap_idle(grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_ap_idle),
    .ap_ready(grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_ap_ready),
    .avg_lts_M_real_V_address0(grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_avg_lts_M_real_V_address0),
    .avg_lts_M_real_V_ce0(grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_avg_lts_M_real_V_ce0),
    .avg_lts_M_real_V_q0(avg_lts_M_real_V_q0),
    .avg_lts_M_imag_V_address0(grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_avg_lts_M_imag_V_address0),
    .avg_lts_M_imag_V_ce0(grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_avg_lts_M_imag_V_ce0),
    .avg_lts_M_imag_V_q0(avg_lts_M_imag_V_q0),
    .new_lts_Addr_A(grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_new_lts_Addr_A),
    .new_lts_EN_A(grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_new_lts_EN_A),
    .new_lts_WEN_A(grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_new_lts_WEN_A),
    .new_lts_Din_A(grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_new_lts_Din_A),
    .new_lts_Dout_A(32'd0)
);

ch_gain_cal_moving_avg grp_moving_avg_fu_126(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_moving_avg_fu_126_ap_start),
    .ap_done(grp_moving_avg_fu_126_ap_done),
    .ap_idle(grp_moving_avg_fu_126_ap_idle),
    .ap_ready(grp_moving_avg_fu_126_ap_ready),
    .iq_samples_in_M_real_address0(grp_moving_avg_fu_126_iq_samples_in_M_real_address0),
    .iq_samples_in_M_real_ce0(grp_moving_avg_fu_126_iq_samples_in_M_real_ce0),
    .iq_samples_in_M_real_q0(avg_lts_M_real_V_q0),
    .iq_samples_in_M_imag_address0(grp_moving_avg_fu_126_iq_samples_in_M_imag_address0),
    .iq_samples_in_M_imag_ce0(grp_moving_avg_fu_126_iq_samples_in_M_imag_ce0),
    .iq_samples_in_M_imag_q0(avg_lts_M_imag_V_q0),
    .iq_samples_out_M_real_0_0_0_address0(grp_moving_avg_fu_126_iq_samples_out_M_real_0_0_0_address0),
    .iq_samples_out_M_real_0_0_0_ce0(grp_moving_avg_fu_126_iq_samples_out_M_real_0_0_0_ce0),
    .iq_samples_out_M_real_0_0_0_we0(grp_moving_avg_fu_126_iq_samples_out_M_real_0_0_0_we0),
    .iq_samples_out_M_real_0_0_0_d0(grp_moving_avg_fu_126_iq_samples_out_M_real_0_0_0_d0),
    .iq_samples_out_M_imag_0_0_0_address0(grp_moving_avg_fu_126_iq_samples_out_M_imag_0_0_0_address0),
    .iq_samples_out_M_imag_0_0_0_ce0(grp_moving_avg_fu_126_iq_samples_out_M_imag_0_0_0_ce0),
    .iq_samples_out_M_imag_0_0_0_we0(grp_moving_avg_fu_126_iq_samples_out_M_imag_0_0_0_we0),
    .iq_samples_out_M_imag_0_0_0_d0(grp_moving_avg_fu_126_iq_samples_out_M_imag_0_0_0_d0),
    .len(len_V_reg_178),
    .arr(grp_moving_avg_fu_126_arr)
);

ch_gain_cal_ch_gain_cal_Pipeline_new_lts_smooth_out grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_ap_start),
    .ap_done(grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_ap_done),
    .ap_idle(grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_ap_idle),
    .ap_ready(grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_ap_ready),
    .first_lts_M_real_V_address0(grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_first_lts_M_real_V_address0),
    .first_lts_M_real_V_ce0(grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_first_lts_M_real_V_ce0),
    .first_lts_M_real_V_q0(first_lts_M_real_V_q0),
    .first_lts_M_imag_V_address0(grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_first_lts_M_imag_V_address0),
    .first_lts_M_imag_V_ce0(grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_first_lts_M_imag_V_ce0),
    .first_lts_M_imag_V_q0(first_lts_M_imag_V_q0),
    .new_lts_Addr_A(grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_new_lts_Addr_A),
    .new_lts_EN_A(grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_new_lts_EN_A),
    .new_lts_WEN_A(grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_new_lts_WEN_A),
    .new_lts_Din_A(grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_new_lts_Din_A),
    .new_lts_Dout_A(32'd0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ch_gain_cal_Pipeline_ht_lts_fu_108_ap_start_reg <= 1'b0;
    end else begin
        if (((ltf_type == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_ch_gain_cal_Pipeline_ht_lts_fu_108_ap_start_reg <= 1'b1;
        end else if ((grp_ch_gain_cal_Pipeline_ht_lts_fu_108_ap_ready == 1'b1)) begin
            grp_ch_gain_cal_Pipeline_ht_lts_fu_108_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ch_gain_cal_Pipeline_l_lts_fu_96_ap_start_reg <= 1'b0;
    end else begin
        if (((ltf_type == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_ch_gain_cal_Pipeline_l_lts_fu_96_ap_start_reg <= 1'b1;
        end else if ((grp_ch_gain_cal_Pipeline_l_lts_fu_96_ap_ready == 1'b1)) begin
            grp_ch_gain_cal_Pipeline_l_lts_fu_96_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_ap_start_reg <= 1'b1;
        end else if ((grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_ap_ready == 1'b1)) begin
            grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_ap_start_reg <= 1'b1;
        end else if ((grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_ap_ready == 1'b1)) begin
            grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_moving_avg_fu_126_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state6))) begin
            grp_moving_avg_fu_126_ap_start_reg <= 1'b1;
        end else if ((grp_moving_avg_fu_126_ap_ready == 1'b1)) begin
            grp_moving_avg_fu_126_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((smooth == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        arr1_reg_183[9] <= arr1_fu_153_p3[9];
        len_V_reg_178[2 : 1] <= len_V_fu_146_p3[2 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        arr2_reg_188[2 : 1] <= arr2_fu_160_p3[2 : 1];
arr2_reg_188[9] <= arr2_fu_160_p3[9];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state11_on_subcall_done)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_moving_avg_fu_126_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_moving_avg_fu_126_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state9))) begin
        avg_lts_M_imag_V_address0 = grp_moving_avg_fu_126_iq_samples_in_M_imag_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        avg_lts_M_imag_V_address0 = grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_avg_lts_M_imag_V_address0;
    end else if (((ltf_type == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        avg_lts_M_imag_V_address0 = grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_imag_V_address0;
    end else if (((ltf_type == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        avg_lts_M_imag_V_address0 = grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_imag_V_address0;
    end else begin
        avg_lts_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state9))) begin
        avg_lts_M_imag_V_ce0 = grp_moving_avg_fu_126_iq_samples_in_M_imag_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        avg_lts_M_imag_V_ce0 = grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_avg_lts_M_imag_V_ce0;
    end else if (((ltf_type == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        avg_lts_M_imag_V_ce0 = grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_imag_V_ce0;
    end else if (((ltf_type == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        avg_lts_M_imag_V_ce0 = grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_imag_V_ce0;
    end else begin
        avg_lts_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((ltf_type == 1'd1)) begin
            avg_lts_M_imag_V_d0 = grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_imag_V_d0;
        end else if ((ltf_type == 1'd0)) begin
            avg_lts_M_imag_V_d0 = grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_imag_V_d0;
        end else begin
            avg_lts_M_imag_V_d0 = 'bx;
        end
    end else begin
        avg_lts_M_imag_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((ltf_type == 1'd1)) begin
            avg_lts_M_imag_V_we0 = grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_imag_V_we0;
        end else if ((ltf_type == 1'd0)) begin
            avg_lts_M_imag_V_we0 = grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_imag_V_we0;
        end else begin
            avg_lts_M_imag_V_we0 = 1'b0;
        end
    end else begin
        avg_lts_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state9))) begin
        avg_lts_M_real_V_address0 = grp_moving_avg_fu_126_iq_samples_in_M_real_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        avg_lts_M_real_V_address0 = grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_avg_lts_M_real_V_address0;
    end else if (((ltf_type == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        avg_lts_M_real_V_address0 = grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_real_V_address0;
    end else if (((ltf_type == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        avg_lts_M_real_V_address0 = grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_real_V_address0;
    end else begin
        avg_lts_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state9))) begin
        avg_lts_M_real_V_ce0 = grp_moving_avg_fu_126_iq_samples_in_M_real_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        avg_lts_M_real_V_ce0 = grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_avg_lts_M_real_V_ce0;
    end else if (((ltf_type == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        avg_lts_M_real_V_ce0 = grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_real_V_ce0;
    end else if (((ltf_type == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        avg_lts_M_real_V_ce0 = grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_real_V_ce0;
    end else begin
        avg_lts_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((ltf_type == 1'd1)) begin
            avg_lts_M_real_V_d0 = grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_real_V_d0;
        end else if ((ltf_type == 1'd0)) begin
            avg_lts_M_real_V_d0 = grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_real_V_d0;
        end else begin
            avg_lts_M_real_V_d0 = 'bx;
        end
    end else begin
        avg_lts_M_real_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((ltf_type == 1'd1)) begin
            avg_lts_M_real_V_we0 = grp_ch_gain_cal_Pipeline_ht_lts_fu_108_avg_lts_M_real_V_we0;
        end else if ((ltf_type == 1'd0)) begin
            avg_lts_M_real_V_we0 = grp_ch_gain_cal_Pipeline_l_lts_fu_96_avg_lts_M_real_V_we0;
        end else begin
            avg_lts_M_real_V_we0 = 1'b0;
        end
    end else begin
        avg_lts_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((smooth == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        first_lts_M_imag_V_address0 = grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_first_lts_M_imag_V_address0;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state9))) begin
        first_lts_M_imag_V_address0 = grp_moving_avg_fu_126_iq_samples_out_M_imag_0_0_0_address0;
    end else if (((ltf_type == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        first_lts_M_imag_V_address0 = grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_imag_V_address0;
    end else begin
        first_lts_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((smooth == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        first_lts_M_imag_V_ce0 = grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_first_lts_M_imag_V_ce0;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state9))) begin
        first_lts_M_imag_V_ce0 = grp_moving_avg_fu_126_iq_samples_out_M_imag_0_0_0_ce0;
    end else if (((ltf_type == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        first_lts_M_imag_V_ce0 = grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_imag_V_ce0;
    end else begin
        first_lts_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ltf_type == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        first_lts_M_imag_V_ce1 = grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_imag_V_ce1;
    end else begin
        first_lts_M_imag_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state9))) begin
        first_lts_M_imag_V_d0 = grp_moving_avg_fu_126_iq_samples_out_M_imag_0_0_0_d0;
    end else if (((ltf_type == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        first_lts_M_imag_V_d0 = grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_imag_V_d0;
    end else begin
        first_lts_M_imag_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state9))) begin
        first_lts_M_imag_V_we0 = grp_moving_avg_fu_126_iq_samples_out_M_imag_0_0_0_we0;
    end else if (((ltf_type == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        first_lts_M_imag_V_we0 = grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_imag_V_we0;
    end else begin
        first_lts_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((smooth == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        first_lts_M_real_V_address0 = grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_first_lts_M_real_V_address0;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state9))) begin
        first_lts_M_real_V_address0 = grp_moving_avg_fu_126_iq_samples_out_M_real_0_0_0_address0;
    end else if (((ltf_type == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        first_lts_M_real_V_address0 = grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_real_V_address0;
    end else begin
        first_lts_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((smooth == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        first_lts_M_real_V_ce0 = grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_first_lts_M_real_V_ce0;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state9))) begin
        first_lts_M_real_V_ce0 = grp_moving_avg_fu_126_iq_samples_out_M_real_0_0_0_ce0;
    end else if (((ltf_type == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        first_lts_M_real_V_ce0 = grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_real_V_ce0;
    end else begin
        first_lts_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ltf_type == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        first_lts_M_real_V_ce1 = grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_real_V_ce1;
    end else begin
        first_lts_M_real_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state9))) begin
        first_lts_M_real_V_d0 = grp_moving_avg_fu_126_iq_samples_out_M_real_0_0_0_d0;
    end else if (((ltf_type == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        first_lts_M_real_V_d0 = grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_real_V_d0;
    end else begin
        first_lts_M_real_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state9))) begin
        first_lts_M_real_V_we0 = grp_moving_avg_fu_126_iq_samples_out_M_real_0_0_0_we0;
    end else if (((ltf_type == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        first_lts_M_real_V_we0 = grp_ch_gain_cal_Pipeline_l_lts_fu_96_first_lts_M_real_V_we0;
    end else begin
        first_lts_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_moving_avg_fu_126_arr = arr2_reg_188;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_moving_avg_fu_126_arr = arr1_reg_183;
    end else begin
        grp_moving_avg_fu_126_arr = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        if ((ltf_type == 1'd1)) begin
            lts_iq_fd_V_read = grp_ch_gain_cal_Pipeline_ht_lts_fu_108_lts_iq_fd_V_read;
        end else if ((ltf_type == 1'd0)) begin
            lts_iq_fd_V_read = grp_ch_gain_cal_Pipeline_l_lts_fu_96_lts_iq_fd_V_read;
        end else begin
            lts_iq_fd_V_read = 1'b0;
        end
    end else begin
        lts_iq_fd_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((smooth == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        new_lts_Addr_A = grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_new_lts_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        new_lts_Addr_A = grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_new_lts_Addr_A;
    end else begin
        new_lts_Addr_A = 'bx;
    end
end

always @ (*) begin
    if (((smooth == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        new_lts_Din_A = grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_new_lts_Din_A;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        new_lts_Din_A = grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_new_lts_Din_A;
    end else begin
        new_lts_Din_A = 'bx;
    end
end

always @ (*) begin
    if (((smooth == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        new_lts_EN_A = grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_new_lts_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        new_lts_EN_A = grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_new_lts_EN_A;
    end else begin
        new_lts_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((smooth == 1'd1) & (1'b1 == ap_CS_fsm_state11))) begin
        new_lts_WEN_A = grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_new_lts_WEN_A;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        new_lts_WEN_A = grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_new_lts_WEN_A;
    end else begin
        new_lts_WEN_A = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((smooth == 1'd1) & (1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if (((smooth_read_read_fu_90_p2 == 1'd0) & (1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_moving_avg_fu_126_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_moving_avg_fu_126_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state11_on_subcall_done = ((smooth == 1'd1) & (grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state3_on_subcall_done = (((ltf_type == 1'd1) & (grp_ch_gain_cal_Pipeline_ht_lts_fu_108_ap_done == 1'b0)) | ((ltf_type == 1'd0) & (grp_ch_gain_cal_Pipeline_l_lts_fu_96_ap_done == 1'b0)));
end

assign arr1_fu_153_p3 = ((ltf_type[0:0] == 1'b1) ? 10'd0 : 10'd512);

assign arr2_fu_160_p3 = ((ltf_type[0:0] == 1'b1) ? 10'd28 : 10'd538);

assign grp_ch_gain_cal_Pipeline_ht_lts_fu_108_ap_start = grp_ch_gain_cal_Pipeline_ht_lts_fu_108_ap_start_reg;

assign grp_ch_gain_cal_Pipeline_l_lts_fu_96_ap_start = grp_ch_gain_cal_Pipeline_l_lts_fu_96_ap_start_reg;

assign grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_ap_start = grp_ch_gain_cal_Pipeline_new_lts_out_fu_118_ap_start_reg;

assign grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_ap_start = grp_ch_gain_cal_Pipeline_new_lts_smooth_out_fu_138_ap_start_reg;

assign grp_moving_avg_fu_126_ap_start = grp_moving_avg_fu_126_ap_start_reg;

assign len_V_fu_146_p3 = ((ltf_type[0:0] == 1'b1) ? 4'd12 : 4'd10);

assign new_lts_Clk_A = ap_clk;

assign new_lts_Rst_A = ap_rst;

assign smooth_read_read_fu_90_p2 = smooth;

always @ (posedge ap_clk) begin
    len_V_reg_178[0] <= 1'b0;
    len_V_reg_178[3] <= 1'b1;
    arr1_reg_183[8:0] <= 9'b000000000;
    arr2_reg_188[0] <= 1'b0;
    arr2_reg_188[8:3] <= 6'b000011;
end

endmodule //ch_gain_cal
